### ISSUE TITLE
Another possible error when cloning

### ISSUE THREAD

**Issue by Nachobr** [Nachobr/marketplacepohubi#2]
![Screenshot_20210709-190224.png](https://user-images.githubusercontent.com/55702500/125140180-4e8f9800-e0e8-11eb-969c-1cc1e3a77bb3.png)

To fix this, You have to Add to metamask ganache localhost network with the private key and password that is shown when You do migrate .. on the terminal of the Main roto source folder, if You don't know how to Add check the link of the vídeo on how to do it.

Another possible error is the Server running on port 4000
(node:28083) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/

Well the error is clear, here You just have to Add your IP to a whitelist in mongodb, going to security then network access

**Comment by david-rivero** [comment]
I think that the description is good. Maybe we need to add this explanation in the README to avoid errors related to this problem with the next developers.
